"""added password field

Revision ID: 527b0e8d4174
Revises: 69bf1f47216e
Create Date: 2025-01-12 15:56:23.664548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527b0e8d4174'
down_revision: Union[str, None] = '69bf1f47216e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_index('ix_urls_original_url', table_name='urls')
    op.create_index(op.f('ix_urls_target_url'), 'urls', ['target_url'], unique=False)
    op.drop_column('urls', 'clicks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_urls_target_url'), table_name='urls')
    op.create_index('ix_urls_original_url', 'urls', ['target_url'], unique=False)
    op.drop_column('urls', 'password_hash')
    # ### end Alembic commands ###
